-- 소속·팀별 문자 보내기에서 쓸 "미리 저장해 둔 메시지".
--
-- 실제 발송은 서버가 하지 않는다. 운영자 휴대폰의 기본 문자 앱을 sms: 링크로
-- 열어 주고, 마지막 전송은 사람이 직접 누른다. 그래서 여기 저장되는 건
-- 메시지 문구뿐이고 발신번호나 API 키 같은 건 필요 없다.

create table if not exists public.bus_sms_templates(
  id         bigint generated by default as identity primary key,
  title      text not null,
  body       text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bus_sms_templates enable row level security;
-- 정책을 두지 않는다. 아래 SECURITY DEFINER 함수(운영 코드로 보호)로만 접근한다.

create or replace function public.bus_sms_admin(p_code text, p_action text,
                                                p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_code  text;
  v_id    bigint;
  v_title text := btrim(coalesce(p_payload->>'title', ''));
  v_body  text := coalesce(p_payload->>'body', '');
begin
  select value into v_code from public.bus_config where key = 'admin_code';
  if v_code is null or p_code is null or p_code <> v_code then
    return jsonb_build_object('status', 'denied');
  end if;

  if p_action = 'list' then
    return jsonb_build_object(
      'status', 'ok',
      'rows', coalesce((select jsonb_agg(jsonb_build_object('id', id, 'title', title, 'body', body)
                                         order by title)
                          from public.bus_sms_templates), '[]'::jsonb));

  elsif p_action = 'save' then
    if v_title = '' or btrim(v_body) = '' then
      return jsonb_build_object('status', 'invalid');
    end if;

    if (p_payload->>'id') is not null then
      update public.bus_sms_templates
         set title = v_title, body = v_body, updated_at = now()
       where id = (p_payload->>'id')::bigint
      returning id into v_id;
      if v_id is null then return jsonb_build_object('status', 'gone'); end if;
      return jsonb_build_object('status', 'ok', 'id', v_id);
    end if;

    insert into public.bus_sms_templates(title, body)
    values (v_title, v_body)
    returning id into v_id;
    return jsonb_build_object('status', 'ok', 'id', v_id);

  elsif p_action = 'del' then
    delete from public.bus_sms_templates where id = (p_payload->>'id')::bigint;
    return jsonb_build_object('status', 'ok');
  end if;

  return jsonb_build_object('status', 'unknown_action');
end;
$$;

revoke all on function public.bus_sms_admin(text, text, jsonb) from public;
grant execute on function public.bus_sms_admin(text, text, jsonb)
  to anon, authenticated, service_role;
